# Generated by Django 5.0.7 on 2024-07-18 14:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="authuser",
            managers=[],
        ),
    ]
