name: Quality Checks

on: [pull_request]

concurrency:
  group: "${{ github.workflow}}-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  quality_checks:
    name: audit code style
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Python V4
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          make install

      - name: Run Audits
        run: |
          make lint
          
      - name: Run Tests
        run: |
          make test
