name: Quality Checks

on: [push, pull_request]

concurrency:
  group: "${{ github.workflow}}-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  quality_checks:
    name: audit code style
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10.14]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Python V4
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          make install

      - name: Ruff check
        uses: chartboost/ruff-action@v1
          
      - name: Run Tests
        run: |
          export DJANGO_SETTINGS_MODULE="tc4a.settings"
          make test
