name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        DJANGO_SETTINGS_MODULE: tc4a.settings
        SECRET_KEY: 'secret_key'
        PRIMARY_DB: 'primary_db'
        PRIMARY_DB_USER: 'primary_db_user'
        PRIMARY_DB_HOST: 'primary_db_host'
        PRIMARY_DB_PORT: 'primary_db_port'
        PRIMARY_DB_USER_PASSWORD: 'primary_db_password'
      run: |
        python manage.py test
